// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.27.0
// source: data/data.proto

package data

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KageDataService_GetMetadata_FullMethodName  = "/kage.data.KageDataService/GetMetadata"
	KageDataService_CommitOffset_FullMethodName = "/kage.data.KageDataService/CommitOffset"
	KageDataService_GetOffset_FullMethodName    = "/kage.data.KageDataService/GetOffset"
	KageDataService_ListOffsets_FullMethodName  = "/kage.data.KageDataService/ListOffsets"
)

// KageDataServiceClient is the client API for KageDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KageDataServiceClient interface {
	// Discovery: Used by clients to locate partition leaders
	GetMetadata(ctx context.Context, in *MetadataRequest, opts ...grpc.CallOption) (*MetadataResponse, error)
	// Offset Management: Persist consumer progress
	CommitOffset(ctx context.Context, in *OffsetCommitRequest, opts ...grpc.CallOption) (*OffsetCommitResponse, error)
	GetOffset(ctx context.Context, in *OffsetFetchRequest, opts ...grpc.CallOption) (*OffsetFetchResponse, error)
	// Utility: Retrieve boundary offsets
	ListOffsets(ctx context.Context, in *ListOffsetsRequest, opts ...grpc.CallOption) (*ListOffsetsResponse, error)
}

type kageDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKageDataServiceClient(cc grpc.ClientConnInterface) KageDataServiceClient {
	return &kageDataServiceClient{cc}
}

func (c *kageDataServiceClient) GetMetadata(ctx context.Context, in *MetadataRequest, opts ...grpc.CallOption) (*MetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetadataResponse)
	err := c.cc.Invoke(ctx, KageDataService_GetMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kageDataServiceClient) CommitOffset(ctx context.Context, in *OffsetCommitRequest, opts ...grpc.CallOption) (*OffsetCommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OffsetCommitResponse)
	err := c.cc.Invoke(ctx, KageDataService_CommitOffset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kageDataServiceClient) GetOffset(ctx context.Context, in *OffsetFetchRequest, opts ...grpc.CallOption) (*OffsetFetchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OffsetFetchResponse)
	err := c.cc.Invoke(ctx, KageDataService_GetOffset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kageDataServiceClient) ListOffsets(ctx context.Context, in *ListOffsetsRequest, opts ...grpc.CallOption) (*ListOffsetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOffsetsResponse)
	err := c.cc.Invoke(ctx, KageDataService_ListOffsets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KageDataServiceServer is the server API for KageDataService service.
// All implementations must embed UnimplementedKageDataServiceServer
// for forward compatibility.
type KageDataServiceServer interface {
	// Discovery: Used by clients to locate partition leaders
	GetMetadata(context.Context, *MetadataRequest) (*MetadataResponse, error)
	// Offset Management: Persist consumer progress
	CommitOffset(context.Context, *OffsetCommitRequest) (*OffsetCommitResponse, error)
	GetOffset(context.Context, *OffsetFetchRequest) (*OffsetFetchResponse, error)
	// Utility: Retrieve boundary offsets
	ListOffsets(context.Context, *ListOffsetsRequest) (*ListOffsetsResponse, error)
	mustEmbedUnimplementedKageDataServiceServer()
}

// UnimplementedKageDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKageDataServiceServer struct{}

func (UnimplementedKageDataServiceServer) GetMetadata(context.Context, *MetadataRequest) (*MetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMetadata not implemented")
}
func (UnimplementedKageDataServiceServer) CommitOffset(context.Context, *OffsetCommitRequest) (*OffsetCommitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitOffset not implemented")
}
func (UnimplementedKageDataServiceServer) GetOffset(context.Context, *OffsetFetchRequest) (*OffsetFetchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOffset not implemented")
}
func (UnimplementedKageDataServiceServer) ListOffsets(context.Context, *ListOffsetsRequest) (*ListOffsetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOffsets not implemented")
}
func (UnimplementedKageDataServiceServer) mustEmbedUnimplementedKageDataServiceServer() {}
func (UnimplementedKageDataServiceServer) testEmbeddedByValue()                         {}

// UnsafeKageDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KageDataServiceServer will
// result in compilation errors.
type UnsafeKageDataServiceServer interface {
	mustEmbedUnimplementedKageDataServiceServer()
}

func RegisterKageDataServiceServer(s grpc.ServiceRegistrar, srv KageDataServiceServer) {
	// If the following call panics, it indicates UnimplementedKageDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KageDataService_ServiceDesc, srv)
}

func _KageDataService_GetMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KageDataServiceServer).GetMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KageDataService_GetMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KageDataServiceServer).GetMetadata(ctx, req.(*MetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KageDataService_CommitOffset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OffsetCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KageDataServiceServer).CommitOffset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KageDataService_CommitOffset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KageDataServiceServer).CommitOffset(ctx, req.(*OffsetCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KageDataService_GetOffset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OffsetFetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KageDataServiceServer).GetOffset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KageDataService_GetOffset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KageDataServiceServer).GetOffset(ctx, req.(*OffsetFetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KageDataService_ListOffsets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOffsetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KageDataServiceServer).ListOffsets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KageDataService_ListOffsets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KageDataServiceServer).ListOffsets(ctx, req.(*ListOffsetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KageDataService_ServiceDesc is the grpc.ServiceDesc for KageDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KageDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kage.data.KageDataService",
	HandlerType: (*KageDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMetadata",
			Handler:    _KageDataService_GetMetadata_Handler,
		},
		{
			MethodName: "CommitOffset",
			Handler:    _KageDataService_CommitOffset_Handler,
		},
		{
			MethodName: "GetOffset",
			Handler:    _KageDataService_GetOffset_Handler,
		},
		{
			MethodName: "ListOffsets",
			Handler:    _KageDataService_ListOffsets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data/data.proto",
}
