// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.0
// source: kadmin/kadmin.proto

package kadmin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTopicRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TopicName         string                 `protobuf:"bytes,1,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	NumPartitions     int32                  `protobuf:"varint,2,opt,name=num_partitions,json=numPartitions,proto3" json:"num_partitions,omitempty"`
	ReplicationFactor int32                  `protobuf:"varint,3,opt,name=replication_factor,json=replicationFactor,proto3" json:"replication_factor,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateTopicRequest) Reset() {
	*x = CreateTopicRequest{}
	mi := &file_kadmin_kadmin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicRequest) ProtoMessage() {}

func (x *CreateTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kadmin_kadmin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicRequest.ProtoReflect.Descriptor instead.
func (*CreateTopicRequest) Descriptor() ([]byte, []int) {
	return file_kadmin_kadmin_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTopicRequest) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *CreateTopicRequest) GetNumPartitions() int32 {
	if x != nil {
		return x.NumPartitions
	}
	return 0
}

func (x *CreateTopicRequest) GetReplicationFactor() int32 {
	if x != nil {
		return x.ReplicationFactor
	}
	return 0
}

type CreateTopicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicResponse) Reset() {
	*x = CreateTopicResponse{}
	mi := &file_kadmin_kadmin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicResponse) ProtoMessage() {}

func (x *CreateTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kadmin_kadmin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicResponse.ProtoReflect.Descriptor instead.
func (*CreateTopicResponse) Descriptor() ([]byte, []int) {
	return file_kadmin_kadmin_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTopicResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateTopicResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicName     string                 `protobuf:"bytes,1,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTopicRequest) Reset() {
	*x = DeleteTopicRequest{}
	mi := &file_kadmin_kadmin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTopicRequest) ProtoMessage() {}

func (x *DeleteTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kadmin_kadmin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTopicRequest.ProtoReflect.Descriptor instead.
func (*DeleteTopicRequest) Descriptor() ([]byte, []int) {
	return file_kadmin_kadmin_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteTopicRequest) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

type DeleteTopicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTopicResponse) Reset() {
	*x = DeleteTopicResponse{}
	mi := &file_kadmin_kadmin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTopicResponse) ProtoMessage() {}

func (x *DeleteTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kadmin_kadmin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTopicResponse.ProtoReflect.Descriptor instead.
func (*DeleteTopicResponse) Descriptor() ([]byte, []int) {
	return file_kadmin_kadmin_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteTopicResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteTopicResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListTopicsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTopicsRequest) Reset() {
	*x = ListTopicsRequest{}
	mi := &file_kadmin_kadmin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopicsRequest) ProtoMessage() {}

func (x *ListTopicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kadmin_kadmin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopicsRequest.ProtoReflect.Descriptor instead.
func (*ListTopicsRequest) Descriptor() ([]byte, []int) {
	return file_kadmin_kadmin_proto_rawDescGZIP(), []int{4}
}

type ListTopicsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []string               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTopicsResponse) Reset() {
	*x = ListTopicsResponse{}
	mi := &file_kadmin_kadmin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopicsResponse) ProtoMessage() {}

func (x *ListTopicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kadmin_kadmin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopicsResponse.ProtoReflect.Descriptor instead.
func (*ListTopicsResponse) Descriptor() ([]byte, []int) {
	return file_kadmin_kadmin_proto_rawDescGZIP(), []int{5}
}

func (x *ListTopicsResponse) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

type DescribeTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicName     string                 `protobuf:"bytes,1,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeTopicRequest) Reset() {
	*x = DescribeTopicRequest{}
	mi := &file_kadmin_kadmin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeTopicRequest) ProtoMessage() {}

func (x *DescribeTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kadmin_kadmin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeTopicRequest.ProtoReflect.Descriptor instead.
func (*DescribeTopicRequest) Descriptor() ([]byte, []int) {
	return file_kadmin_kadmin_proto_rawDescGZIP(), []int{6}
}

func (x *DescribeTopicRequest) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

type DescribeTopicResponse struct {
	state             protoimpl.MessageState   `protogen:"open.v1"`
	TopicName         string                   `protobuf:"bytes,1,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	NumPartitions     int32                    `protobuf:"varint,2,opt,name=num_partitions,json=numPartitions,proto3" json:"num_partitions,omitempty"`
	ReplicationFactor int32                    `protobuf:"varint,3,opt,name=replication_factor,json=replicationFactor,proto3" json:"replication_factor,omitempty"`
	Partitions        map[int32]*PartitionInfo `protobuf:"bytes,4,rep,name=partitions,proto3" json:"partitions,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DescribeTopicResponse) Reset() {
	*x = DescribeTopicResponse{}
	mi := &file_kadmin_kadmin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeTopicResponse) ProtoMessage() {}

func (x *DescribeTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kadmin_kadmin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeTopicResponse.ProtoReflect.Descriptor instead.
func (*DescribeTopicResponse) Descriptor() ([]byte, []int) {
	return file_kadmin_kadmin_proto_rawDescGZIP(), []int{7}
}

func (x *DescribeTopicResponse) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *DescribeTopicResponse) GetNumPartitions() int32 {
	if x != nil {
		return x.NumPartitions
	}
	return 0
}

func (x *DescribeTopicResponse) GetReplicationFactor() int32 {
	if x != nil {
		return x.ReplicationFactor
	}
	return 0
}

func (x *DescribeTopicResponse) GetPartitions() map[int32]*PartitionInfo {
	if x != nil {
		return x.Partitions
	}
	return nil
}

type PartitionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartitionId   int32                  `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	Leader        int32                  `protobuf:"varint,2,opt,name=leader,proto3" json:"leader,omitempty"`
	Replicas      []int32                `protobuf:"varint,3,rep,packed,name=replicas,proto3" json:"replicas,omitempty"`
	Isr           []int32                `protobuf:"varint,4,rep,packed,name=isr,proto3" json:"isr,omitempty"` // In-Sync Replicas
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionInfo) Reset() {
	*x = PartitionInfo{}
	mi := &file_kadmin_kadmin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionInfo) ProtoMessage() {}

func (x *PartitionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_kadmin_kadmin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionInfo.ProtoReflect.Descriptor instead.
func (*PartitionInfo) Descriptor() ([]byte, []int) {
	return file_kadmin_kadmin_proto_rawDescGZIP(), []int{8}
}

func (x *PartitionInfo) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *PartitionInfo) GetLeader() int32 {
	if x != nil {
		return x.Leader
	}
	return 0
}

func (x *PartitionInfo) GetReplicas() []int32 {
	if x != nil {
		return x.Replicas
	}
	return nil
}

func (x *PartitionInfo) GetIsr() []int32 {
	if x != nil {
		return x.Isr
	}
	return nil
}

type GetClusterInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterInfoRequest) Reset() {
	*x = GetClusterInfoRequest{}
	mi := &file_kadmin_kadmin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterInfoRequest) ProtoMessage() {}

func (x *GetClusterInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kadmin_kadmin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterInfoRequest.ProtoReflect.Descriptor instead.
func (*GetClusterInfoRequest) Descriptor() ([]byte, []int) {
	return file_kadmin_kadmin_proto_rawDescGZIP(), []int{9}
}

type GetClusterInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Brokers       []*BrokerInfo          `protobuf:"bytes,2,rep,name=brokers,proto3" json:"brokers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterInfoResponse) Reset() {
	*x = GetClusterInfoResponse{}
	mi := &file_kadmin_kadmin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterInfoResponse) ProtoMessage() {}

func (x *GetClusterInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kadmin_kadmin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterInfoResponse.ProtoReflect.Descriptor instead.
func (*GetClusterInfoResponse) Descriptor() ([]byte, []int) {
	return file_kadmin_kadmin_proto_rawDescGZIP(), []int{10}
}

func (x *GetClusterInfoResponse) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *GetClusterInfoResponse) GetBrokers() []*BrokerInfo {
	if x != nil {
		return x.Brokers
	}
	return nil
}

type BrokerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrokerId      int32                  `protobuf:"varint,1,opt,name=broker_id,json=brokerId,proto3" json:"broker_id,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrokerInfo) Reset() {
	*x = BrokerInfo{}
	mi := &file_kadmin_kadmin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrokerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerInfo) ProtoMessage() {}

func (x *BrokerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_kadmin_kadmin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerInfo.ProtoReflect.Descriptor instead.
func (*BrokerInfo) Descriptor() ([]byte, []int) {
	return file_kadmin_kadmin_proto_rawDescGZIP(), []int{11}
}

func (x *BrokerInfo) GetBrokerId() int32 {
	if x != nil {
		return x.BrokerId
	}
	return 0
}

func (x *BrokerInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *BrokerInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

var File_kadmin_kadmin_proto protoreflect.FileDescriptor

const file_kadmin_kadmin_proto_rawDesc = "" +
	"\n" +
	"\x13kadmin/kadmin.proto\x12\vkage.kadmin\"\x89\x01\n" +
	"\x12CreateTopicRequest\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x01 \x01(\tR\ttopicName\x12%\n" +
	"\x0enum_partitions\x18\x02 \x01(\x05R\rnumPartitions\x12-\n" +
	"\x12replication_factor\x18\x03 \x01(\x05R\x11replicationFactor\"I\n" +
	"\x13CreateTopicResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"3\n" +
	"\x12DeleteTopicRequest\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x01 \x01(\tR\ttopicName\"I\n" +
	"\x13DeleteTopicResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x13\n" +
	"\x11ListTopicsRequest\",\n" +
	"\x12ListTopicsResponse\x12\x16\n" +
	"\x06topics\x18\x01 \x03(\tR\x06topics\"5\n" +
	"\x14DescribeTopicRequest\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x01 \x01(\tR\ttopicName\"\xbb\x02\n" +
	"\x15DescribeTopicResponse\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x01 \x01(\tR\ttopicName\x12%\n" +
	"\x0enum_partitions\x18\x02 \x01(\x05R\rnumPartitions\x12-\n" +
	"\x12replication_factor\x18\x03 \x01(\x05R\x11replicationFactor\x12R\n" +
	"\n" +
	"partitions\x18\x04 \x03(\v22.kage.kadmin.DescribeTopicResponse.PartitionsEntryR\n" +
	"partitions\x1aY\n" +
	"\x0fPartitionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.kage.kadmin.PartitionInfoR\x05value:\x028\x01\"x\n" +
	"\rPartitionInfo\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\x05R\vpartitionId\x12\x16\n" +
	"\x06leader\x18\x02 \x01(\x05R\x06leader\x12\x1a\n" +
	"\breplicas\x18\x03 \x03(\x05R\breplicas\x12\x10\n" +
	"\x03isr\x18\x04 \x03(\x05R\x03isr\"\x17\n" +
	"\x15GetClusterInfoRequest\"j\n" +
	"\x16GetClusterInfoResponse\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x121\n" +
	"\abrokers\x18\x02 \x03(\v2\x17.kage.kadmin.BrokerInfoR\abrokers\"Q\n" +
	"\n" +
	"BrokerInfo\x12\x1b\n" +
	"\tbroker_id\x18\x01 \x01(\x05R\bbrokerId\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port2\xb2\x03\n" +
	"\n" +
	"KafkaAdmin\x12P\n" +
	"\vCreateTopic\x12\x1f.kage.kadmin.CreateTopicRequest\x1a .kage.kadmin.CreateTopicResponse\x12P\n" +
	"\vDeleteTopic\x12\x1f.kage.kadmin.DeleteTopicRequest\x1a .kage.kadmin.DeleteTopicResponse\x12M\n" +
	"\n" +
	"ListTopics\x12\x1e.kage.kadmin.ListTopicsRequest\x1a\x1f.kage.kadmin.ListTopicsResponse\x12V\n" +
	"\rDescribeTopic\x12!.kage.kadmin.DescribeTopicRequest\x1a\".kage.kadmin.DescribeTopicResponse\x12Y\n" +
	"\x0eGetClusterInfo\x12\".kage.kadmin.GetClusterInfoRequest\x1a#.kage.kadmin.GetClusterInfoResponseB\x11Z\x0fkage/rpc/kadminb\x06proto3"

var (
	file_kadmin_kadmin_proto_rawDescOnce sync.Once
	file_kadmin_kadmin_proto_rawDescData []byte
)

func file_kadmin_kadmin_proto_rawDescGZIP() []byte {
	file_kadmin_kadmin_proto_rawDescOnce.Do(func() {
		file_kadmin_kadmin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kadmin_kadmin_proto_rawDesc), len(file_kadmin_kadmin_proto_rawDesc)))
	})
	return file_kadmin_kadmin_proto_rawDescData
}

var file_kadmin_kadmin_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_kadmin_kadmin_proto_goTypes = []any{
	(*CreateTopicRequest)(nil),     // 0: kage.kadmin.CreateTopicRequest
	(*CreateTopicResponse)(nil),    // 1: kage.kadmin.CreateTopicResponse
	(*DeleteTopicRequest)(nil),     // 2: kage.kadmin.DeleteTopicRequest
	(*DeleteTopicResponse)(nil),    // 3: kage.kadmin.DeleteTopicResponse
	(*ListTopicsRequest)(nil),      // 4: kage.kadmin.ListTopicsRequest
	(*ListTopicsResponse)(nil),     // 5: kage.kadmin.ListTopicsResponse
	(*DescribeTopicRequest)(nil),   // 6: kage.kadmin.DescribeTopicRequest
	(*DescribeTopicResponse)(nil),  // 7: kage.kadmin.DescribeTopicResponse
	(*PartitionInfo)(nil),          // 8: kage.kadmin.PartitionInfo
	(*GetClusterInfoRequest)(nil),  // 9: kage.kadmin.GetClusterInfoRequest
	(*GetClusterInfoResponse)(nil), // 10: kage.kadmin.GetClusterInfoResponse
	(*BrokerInfo)(nil),             // 11: kage.kadmin.BrokerInfo
	nil,                            // 12: kage.kadmin.DescribeTopicResponse.PartitionsEntry
}
var file_kadmin_kadmin_proto_depIdxs = []int32{
	12, // 0: kage.kadmin.DescribeTopicResponse.partitions:type_name -> kage.kadmin.DescribeTopicResponse.PartitionsEntry
	11, // 1: kage.kadmin.GetClusterInfoResponse.brokers:type_name -> kage.kadmin.BrokerInfo
	8,  // 2: kage.kadmin.DescribeTopicResponse.PartitionsEntry.value:type_name -> kage.kadmin.PartitionInfo
	0,  // 3: kage.kadmin.KafkaAdmin.CreateTopic:input_type -> kage.kadmin.CreateTopicRequest
	2,  // 4: kage.kadmin.KafkaAdmin.DeleteTopic:input_type -> kage.kadmin.DeleteTopicRequest
	4,  // 5: kage.kadmin.KafkaAdmin.ListTopics:input_type -> kage.kadmin.ListTopicsRequest
	6,  // 6: kage.kadmin.KafkaAdmin.DescribeTopic:input_type -> kage.kadmin.DescribeTopicRequest
	9,  // 7: kage.kadmin.KafkaAdmin.GetClusterInfo:input_type -> kage.kadmin.GetClusterInfoRequest
	1,  // 8: kage.kadmin.KafkaAdmin.CreateTopic:output_type -> kage.kadmin.CreateTopicResponse
	3,  // 9: kage.kadmin.KafkaAdmin.DeleteTopic:output_type -> kage.kadmin.DeleteTopicResponse
	5,  // 10: kage.kadmin.KafkaAdmin.ListTopics:output_type -> kage.kadmin.ListTopicsResponse
	7,  // 11: kage.kadmin.KafkaAdmin.DescribeTopic:output_type -> kage.kadmin.DescribeTopicResponse
	10, // 12: kage.kadmin.KafkaAdmin.GetClusterInfo:output_type -> kage.kadmin.GetClusterInfoResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_kadmin_kadmin_proto_init() }
func file_kadmin_kadmin_proto_init() {
	if File_kadmin_kadmin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kadmin_kadmin_proto_rawDesc), len(file_kadmin_kadmin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kadmin_kadmin_proto_goTypes,
		DependencyIndexes: file_kadmin_kadmin_proto_depIdxs,
		MessageInfos:      file_kadmin_kadmin_proto_msgTypes,
	}.Build()
	File_kadmin_kadmin_proto = out.File
	file_kadmin_kadmin_proto_goTypes = nil
	file_kadmin_kadmin_proto_depIdxs = nil
}
