// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/data.proto

package kadmin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []string               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataRequest) Reset() {
	*x = MetadataRequest{}
	mi := &file_api_proto_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataRequest) ProtoMessage() {}

func (x *MetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataRequest.ProtoReflect.Descriptor instead.
func (*MetadataRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_data_proto_rawDescGZIP(), []int{0}
}

func (x *MetadataRequest) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

type MetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brokers       []*Broker              `protobuf:"bytes,1,rep,name=brokers,proto3" json:"brokers,omitempty"`
	Topics        []*TopicMetadata       `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataResponse) Reset() {
	*x = MetadataResponse{}
	mi := &file_api_proto_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataResponse) ProtoMessage() {}

func (x *MetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataResponse.ProtoReflect.Descriptor instead.
func (*MetadataResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_data_proto_rawDescGZIP(), []int{1}
}

func (x *MetadataResponse) GetBrokers() []*Broker {
	if x != nil {
		return x.Brokers
	}
	return nil
}

func (x *MetadataResponse) GetTopics() []*TopicMetadata {
	if x != nil {
		return x.Topics
	}
	return nil
}

type Broker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Broker) Reset() {
	*x = Broker{}
	mi := &file_api_proto_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Broker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Broker) ProtoMessage() {}

func (x *Broker) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Broker.ProtoReflect.Descriptor instead.
func (*Broker) Descriptor() ([]byte, []int) {
	return file_api_proto_data_proto_rawDescGZIP(), []int{2}
}

func (x *Broker) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Broker) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Broker) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type TopicMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Partitions    []*PartitionMetadata   `protobuf:"bytes,2,rep,name=partitions,proto3" json:"partitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicMetadata) Reset() {
	*x = TopicMetadata{}
	mi := &file_api_proto_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicMetadata) ProtoMessage() {}

func (x *TopicMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicMetadata.ProtoReflect.Descriptor instead.
func (*TopicMetadata) Descriptor() ([]byte, []int) {
	return file_api_proto_data_proto_rawDescGZIP(), []int{3}
}

func (x *TopicMetadata) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *TopicMetadata) GetPartitions() []*PartitionMetadata {
	if x != nil {
		return x.Partitions
	}
	return nil
}

type PartitionMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartitionId   int32                  `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	LeaderId      int32                  `protobuf:"varint,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	Replicas      []int32                `protobuf:"varint,3,rep,packed,name=replicas,proto3" json:"replicas,omitempty"`
	Isr           []int32                `protobuf:"varint,4,rep,packed,name=isr,proto3" json:"isr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionMetadata) Reset() {
	*x = PartitionMetadata{}
	mi := &file_api_proto_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionMetadata) ProtoMessage() {}

func (x *PartitionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionMetadata.ProtoReflect.Descriptor instead.
func (*PartitionMetadata) Descriptor() ([]byte, []int) {
	return file_api_proto_data_proto_rawDescGZIP(), []int{4}
}

func (x *PartitionMetadata) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *PartitionMetadata) GetLeaderId() int32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *PartitionMetadata) GetReplicas() []int32 {
	if x != nil {
		return x.Replicas
	}
	return nil
}

func (x *PartitionMetadata) GetIsr() []int32 {
	if x != nil {
		return x.Isr
	}
	return nil
}

type ProduceRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Topic     string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition int32                  `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	// acks: 0 (none), 1 (leader only), -1 (all ISR/Raft quorum)
	RequiredAcks  int32     `protobuf:"varint,3,opt,name=required_acks,json=requiredAcks,proto3" json:"required_acks,omitempty"`
	TimeoutMs     int32     `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	Records       []*Record `protobuf:"bytes,5,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProduceRequest) Reset() {
	*x = ProduceRequest{}
	mi := &file_api_proto_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceRequest) ProtoMessage() {}

func (x *ProduceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceRequest.ProtoReflect.Descriptor instead.
func (*ProduceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_data_proto_rawDescGZIP(), []int{5}
}

func (x *ProduceRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ProduceRequest) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *ProduceRequest) GetRequiredAcks() int32 {
	if x != nil {
		return x.RequiredAcks
	}
	return 0
}

func (x *ProduceRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *ProduceRequest) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_api_proto_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_api_proto_data_proto_rawDescGZIP(), []int{6}
}

func (x *Record) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Record) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Record) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Record) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type ProduceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseOffset    int64                  `protobuf:"varint,1,opt,name=base_offset,json=baseOffset,proto3" json:"base_offset,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProduceResponse) Reset() {
	*x = ProduceResponse{}
	mi := &file_api_proto_data_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceResponse) ProtoMessage() {}

func (x *ProduceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_data_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceResponse.ProtoReflect.Descriptor instead.
func (*ProduceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_data_proto_rawDescGZIP(), []int{7}
}

func (x *ProduceResponse) GetBaseOffset() int64 {
	if x != nil {
		return x.BaseOffset
	}
	return 0
}

func (x *ProduceResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ProduceResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition     int32                  `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	FetchOffset   int64                  `protobuf:"varint,3,opt,name=fetch_offset,json=fetchOffset,proto3" json:"fetch_offset,omitempty"`
	MaxBytes      int32                  `protobuf:"varint,4,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	MinBytes      int32                  `protobuf:"varint,5,opt,name=min_bytes,json=minBytes,proto3" json:"min_bytes,omitempty"`
	MaxWaitMs     int32                  `protobuf:"varint,6,opt,name=max_wait_ms,json=maxWaitMs,proto3" json:"max_wait_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_api_proto_data_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_data_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_data_proto_rawDescGZIP(), []int{8}
}

func (x *FetchRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *FetchRequest) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *FetchRequest) GetFetchOffset() int64 {
	if x != nil {
		return x.FetchOffset
	}
	return 0
}

func (x *FetchRequest) GetMaxBytes() int32 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

func (x *FetchRequest) GetMinBytes() int32 {
	if x != nil {
		return x.MinBytes
	}
	return 0
}

func (x *FetchRequest) GetMaxWaitMs() int32 {
	if x != nil {
		return x.MaxWaitMs
	}
	return 0
}

type FetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*FetchRecord         `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	HighWatermark int64                  `protobuf:"varint,2,opt,name=high_watermark,json=highWatermark,proto3" json:"high_watermark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	mi := &file_api_proto_data_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_data_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_data_proto_rawDescGZIP(), []int{9}
}

func (x *FetchResponse) GetRecords() []*FetchRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *FetchResponse) GetHighWatermark() int64 {
	if x != nil {
		return x.HighWatermark
	}
	return 0
}

type FetchRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRecord) Reset() {
	*x = FetchRecord{}
	mi := &file_api_proto_data_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRecord) ProtoMessage() {}

func (x *FetchRecord) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_data_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRecord.ProtoReflect.Descriptor instead.
func (*FetchRecord) Descriptor() ([]byte, []int) {
	return file_api_proto_data_proto_rawDescGZIP(), []int{10}
}

func (x *FetchRecord) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FetchRecord) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *FetchRecord) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *FetchRecord) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *FetchRecord) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type OffsetCommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerGroup string                 `protobuf:"bytes,1,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition     int32                  `protobuf:"varint,3,opt,name=partition,proto3" json:"partition,omitempty"`
	Offset        int64                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Metadata      string                 `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OffsetCommitRequest) Reset() {
	*x = OffsetCommitRequest{}
	mi := &file_api_proto_data_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OffsetCommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OffsetCommitRequest) ProtoMessage() {}

func (x *OffsetCommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_data_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OffsetCommitRequest.ProtoReflect.Descriptor instead.
func (*OffsetCommitRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_data_proto_rawDescGZIP(), []int{11}
}

func (x *OffsetCommitRequest) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

func (x *OffsetCommitRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *OffsetCommitRequest) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *OffsetCommitRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *OffsetCommitRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type OffsetCommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OffsetCommitResponse) Reset() {
	*x = OffsetCommitResponse{}
	mi := &file_api_proto_data_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OffsetCommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OffsetCommitResponse) ProtoMessage() {}

func (x *OffsetCommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_data_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OffsetCommitResponse.ProtoReflect.Descriptor instead.
func (*OffsetCommitResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_data_proto_rawDescGZIP(), []int{12}
}

func (x *OffsetCommitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type OffsetFetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerGroup string                 `protobuf:"bytes,1,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition     int32                  `protobuf:"varint,3,opt,name=partition,proto3" json:"partition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OffsetFetchRequest) Reset() {
	*x = OffsetFetchRequest{}
	mi := &file_api_proto_data_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OffsetFetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OffsetFetchRequest) ProtoMessage() {}

func (x *OffsetFetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_data_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OffsetFetchRequest.ProtoReflect.Descriptor instead.
func (*OffsetFetchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_data_proto_rawDescGZIP(), []int{13}
}

func (x *OffsetFetchRequest) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

func (x *OffsetFetchRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *OffsetFetchRequest) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

type OffsetFetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OffsetFetchResponse) Reset() {
	*x = OffsetFetchResponse{}
	mi := &file_api_proto_data_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OffsetFetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OffsetFetchResponse) ProtoMessage() {}

func (x *OffsetFetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_data_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OffsetFetchResponse.ProtoReflect.Descriptor instead.
func (*OffsetFetchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_data_proto_rawDescGZIP(), []int{14}
}

func (x *OffsetFetchResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListOffsetsRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Topic     string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition int32                  `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	// -1: Latest, -2: Earliest
	Strategy      int64 `protobuf:"varint,3,opt,name=strategy,proto3" json:"strategy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOffsetsRequest) Reset() {
	*x = ListOffsetsRequest{}
	mi := &file_api_proto_data_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOffsetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOffsetsRequest) ProtoMessage() {}

func (x *ListOffsetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_data_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOffsetsRequest.ProtoReflect.Descriptor instead.
func (*ListOffsetsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_data_proto_rawDescGZIP(), []int{15}
}

func (x *ListOffsetsRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ListOffsetsRequest) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *ListOffsetsRequest) GetStrategy() int64 {
	if x != nil {
		return x.Strategy
	}
	return 0
}

type ListOffsetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOffsetsResponse) Reset() {
	*x = ListOffsetsResponse{}
	mi := &file_api_proto_data_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOffsetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOffsetsResponse) ProtoMessage() {}

func (x *ListOffsetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_data_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOffsetsResponse.ProtoReflect.Descriptor instead.
func (*ListOffsetsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_data_proto_rawDescGZIP(), []int{16}
}

func (x *ListOffsetsResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

var File_api_proto_data_proto protoreflect.FileDescriptor

const file_api_proto_data_proto_rawDesc = "" +
	"\n" +
	"\x14api/proto/data.proto\x12\tkage.data\")\n" +
	"\x0fMetadataRequest\x12\x16\n" +
	"\x06topics\x18\x01 \x03(\tR\x06topics\"q\n" +
	"\x10MetadataResponse\x12+\n" +
	"\abrokers\x18\x01 \x03(\v2\x11.kage.data.BrokerR\abrokers\x120\n" +
	"\x06topics\x18\x02 \x03(\v2\x18.kage.data.TopicMetadataR\x06topics\"@\n" +
	"\x06Broker\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\"c\n" +
	"\rTopicMetadata\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12<\n" +
	"\n" +
	"partitions\x18\x02 \x03(\v2\x1c.kage.data.PartitionMetadataR\n" +
	"partitions\"\x81\x01\n" +
	"\x11PartitionMetadata\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\x05R\vpartitionId\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\x05R\bleaderId\x12\x1a\n" +
	"\breplicas\x18\x03 \x03(\x05R\breplicas\x12\x10\n" +
	"\x03isr\x18\x04 \x03(\x05R\x03isr\"\xb5\x01\n" +
	"\x0eProduceRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\x05R\tpartition\x12#\n" +
	"\rrequired_acks\x18\x03 \x01(\x05R\frequiredAcks\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\x05R\ttimeoutMs\x12+\n" +
	"\arecords\x18\x05 \x03(\v2\x11.kage.data.RecordR\arecords\"\xc4\x01\n" +
	"\x06Record\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x128\n" +
	"\aheaders\x18\x04 \x03(\v2\x1e.kage.data.Record.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"o\n" +
	"\x0fProduceResponse\x12\x1f\n" +
	"\vbase_offset\x18\x01 \x01(\x03R\n" +
	"baseOffset\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\"\xbf\x01\n" +
	"\fFetchRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\x05R\tpartition\x12!\n" +
	"\ffetch_offset\x18\x03 \x01(\x03R\vfetchOffset\x12\x1b\n" +
	"\tmax_bytes\x18\x04 \x01(\x05R\bmaxBytes\x12\x1b\n" +
	"\tmin_bytes\x18\x05 \x01(\x05R\bminBytes\x12\x1e\n" +
	"\vmax_wait_ms\x18\x06 \x01(\x05R\tmaxWaitMs\"h\n" +
	"\rFetchResponse\x120\n" +
	"\arecords\x18\x01 \x03(\v2\x16.kage.data.FetchRecordR\arecords\x12%\n" +
	"\x0ehigh_watermark\x18\x02 \x01(\x03R\rhighWatermark\"\xe6\x01\n" +
	"\vFetchRecord\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12=\n" +
	"\aheaders\x18\x05 \x03(\v2#.kage.data.FetchRecord.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa4\x01\n" +
	"\x13OffsetCommitRequest\x12%\n" +
	"\x0econsumer_group\x18\x01 \x01(\tR\rconsumerGroup\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x03 \x01(\x05R\tpartition\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x03R\x06offset\x12\x1a\n" +
	"\bmetadata\x18\x05 \x01(\tR\bmetadata\"0\n" +
	"\x14OffsetCommitResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"o\n" +
	"\x12OffsetFetchRequest\x12%\n" +
	"\x0econsumer_group\x18\x01 \x01(\tR\rconsumerGroup\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x03 \x01(\x05R\tpartition\"-\n" +
	"\x13OffsetFetchResponse\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\"d\n" +
	"\x12ListOffsetsRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\x05R\tpartition\x12\x1a\n" +
	"\bstrategy\x18\x03 \x01(\x03R\bstrategy\"-\n" +
	"\x13ListOffsetsResponse\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset2\xc2\x03\n" +
	"\x0fKageDataService\x12F\n" +
	"\vGetMetadata\x12\x1a.kage.data.MetadataRequest\x1a\x1b.kage.data.MetadataResponse\x12@\n" +
	"\aProduce\x12\x19.kage.data.ProduceRequest\x1a\x1a.kage.data.ProduceResponse\x12:\n" +
	"\x05Fetch\x12\x17.kage.data.FetchRequest\x1a\x18.kage.data.FetchResponse\x12O\n" +
	"\fCommitOffset\x12\x1e.kage.data.OffsetCommitRequest\x1a\x1f.kage.data.OffsetCommitResponse\x12J\n" +
	"\tGetOffset\x12\x1d.kage.data.OffsetFetchRequest\x1a\x1e.kage.data.OffsetFetchResponse\x12L\n" +
	"\vListOffsets\x12\x1d.kage.data.ListOffsetsRequest\x1a\x1e.kage.data.ListOffsetsResponseB\x11Z\x0fkage/rpc/kadminb\x06proto3"

var (
	file_api_proto_data_proto_rawDescOnce sync.Once
	file_api_proto_data_proto_rawDescData []byte
)

func file_api_proto_data_proto_rawDescGZIP() []byte {
	file_api_proto_data_proto_rawDescOnce.Do(func() {
		file_api_proto_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_data_proto_rawDesc), len(file_api_proto_data_proto_rawDesc)))
	})
	return file_api_proto_data_proto_rawDescData
}

var file_api_proto_data_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_api_proto_data_proto_goTypes = []any{
	(*MetadataRequest)(nil),      // 0: kage.data.MetadataRequest
	(*MetadataResponse)(nil),     // 1: kage.data.MetadataResponse
	(*Broker)(nil),               // 2: kage.data.Broker
	(*TopicMetadata)(nil),        // 3: kage.data.TopicMetadata
	(*PartitionMetadata)(nil),    // 4: kage.data.PartitionMetadata
	(*ProduceRequest)(nil),       // 5: kage.data.ProduceRequest
	(*Record)(nil),               // 6: kage.data.Record
	(*ProduceResponse)(nil),      // 7: kage.data.ProduceResponse
	(*FetchRequest)(nil),         // 8: kage.data.FetchRequest
	(*FetchResponse)(nil),        // 9: kage.data.FetchResponse
	(*FetchRecord)(nil),          // 10: kage.data.FetchRecord
	(*OffsetCommitRequest)(nil),  // 11: kage.data.OffsetCommitRequest
	(*OffsetCommitResponse)(nil), // 12: kage.data.OffsetCommitResponse
	(*OffsetFetchRequest)(nil),   // 13: kage.data.OffsetFetchRequest
	(*OffsetFetchResponse)(nil),  // 14: kage.data.OffsetFetchResponse
	(*ListOffsetsRequest)(nil),   // 15: kage.data.ListOffsetsRequest
	(*ListOffsetsResponse)(nil),  // 16: kage.data.ListOffsetsResponse
	nil,                          // 17: kage.data.Record.HeadersEntry
	nil,                          // 18: kage.data.FetchRecord.HeadersEntry
}
var file_api_proto_data_proto_depIdxs = []int32{
	2,  // 0: kage.data.MetadataResponse.brokers:type_name -> kage.data.Broker
	3,  // 1: kage.data.MetadataResponse.topics:type_name -> kage.data.TopicMetadata
	4,  // 2: kage.data.TopicMetadata.partitions:type_name -> kage.data.PartitionMetadata
	6,  // 3: kage.data.ProduceRequest.records:type_name -> kage.data.Record
	17, // 4: kage.data.Record.headers:type_name -> kage.data.Record.HeadersEntry
	10, // 5: kage.data.FetchResponse.records:type_name -> kage.data.FetchRecord
	18, // 6: kage.data.FetchRecord.headers:type_name -> kage.data.FetchRecord.HeadersEntry
	0,  // 7: kage.data.KageDataService.GetMetadata:input_type -> kage.data.MetadataRequest
	5,  // 8: kage.data.KageDataService.Produce:input_type -> kage.data.ProduceRequest
	8,  // 9: kage.data.KageDataService.Fetch:input_type -> kage.data.FetchRequest
	11, // 10: kage.data.KageDataService.CommitOffset:input_type -> kage.data.OffsetCommitRequest
	13, // 11: kage.data.KageDataService.GetOffset:input_type -> kage.data.OffsetFetchRequest
	15, // 12: kage.data.KageDataService.ListOffsets:input_type -> kage.data.ListOffsetsRequest
	1,  // 13: kage.data.KageDataService.GetMetadata:output_type -> kage.data.MetadataResponse
	7,  // 14: kage.data.KageDataService.Produce:output_type -> kage.data.ProduceResponse
	9,  // 15: kage.data.KageDataService.Fetch:output_type -> kage.data.FetchResponse
	12, // 16: kage.data.KageDataService.CommitOffset:output_type -> kage.data.OffsetCommitResponse
	14, // 17: kage.data.KageDataService.GetOffset:output_type -> kage.data.OffsetFetchResponse
	16, // 18: kage.data.KageDataService.ListOffsets:output_type -> kage.data.ListOffsetsResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_proto_data_proto_init() }
func file_api_proto_data_proto_init() {
	if File_api_proto_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_data_proto_rawDesc), len(file_api_proto_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_data_proto_goTypes,
		DependencyIndexes: file_api_proto_data_proto_depIdxs,
		MessageInfos:      file_api_proto_data_proto_msgTypes,
	}.Build()
	File_api_proto_data_proto = out.File
	file_api_proto_data_proto_goTypes = nil
	file_api_proto_data_proto_depIdxs = nil
}
